### ISSUE TITLE
upgrade sourmash_databases soon (for sourmash 4.0)

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash_databases#10]
ref https://github.com/dib-lab/sourmash/issues/970

**Comment by luizirber** [comment]
I'm working on #7 in #11, would also solve this one.

**Comment by luizirber** [comment]
From https://github.com/dib-lab/sourmash/issues/778: what `bfsize` should we use?

for refseq-archaea:
x1e6 = 135MB
x1e5 = 56MB
x1e4 = 31MB

(and I'm always using `d=2`, I'm not even putting that in the updated Snakefile)

**Comment by luizirber** [comment]
Starting to think we should use `1e6`, it is way faster...

**Comment by luizirber** [comment]
ok, so `1e6` might be faster, but the `bacteria` databases are... very big. This is for `refseq`:
`1e6`: 26.5 GB
`1e5`: 11.7 GB
`1e4`: 7 GB
(and `genbank` will be even larger)

One alternative would be distributing `1e4` and instruct users on how to "upgrade" it to `1e6`, but I don't think it would be upgraded very frequently (and people would just stick to `1e4` because it's ready to use).

Related discussion: https://github.com/dib-lab/sourmash/issues/985#issuecomment-626215382 and the leaf-only databases, and run `prepare` before using it.

**Comment by luizirber** [comment]
> for refseq-archaea:
> x1e6 = 135MB
> x1e5 = 56MB
> x1e4 = 31MB

I ran some `gather` queries with these ones:
`1e6`: 4m52s
`1e5`: 8m
`1e4`: 16m46s

so maybe sticking with `1e5` as a compromise between size and speed?

**Comment by luizirber** [comment]
twitter feedback: https://twitter.com/ctitusbrown/status/1285262175204806658

**Comment by ctb** [comment]
> twitter feedback: https://twitter.com/ctitusbrown/status/1285262175204806658

hah! no feedback. sad.

**Comment by ctb** [comment]
closing in favor of https://github.com/sourmash-bio/sourmash/issues/2015.
